version: "3"
 
services: 
    nginx:
        image: nginx
        volumes:
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - front
            - backend
        ports:
            - 80:80
 
    apache:
        build: ./docker/apache
        volumes:
            - ./:/var/www/
            - ./docker/apache/php.ini:/usr/local/etc/php/php.ini
        networks:
            - backend
 
    db:
        image: "mysql:5.7"
        volumes:
            - ./docker/db:/var/lib/mysql
        environment:
               MYSQL_ROOT_PASSWORD: root
               MYSQL_DATABASE: wp_db
               MYSQL_USER: scam
               MYSQL_PASSWORD: 616622AsD
        networks:
            - backend
 
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            - PMA_HOST=db
            - PMA_USER=scamii
            - PMA_PASSWORD=616622AsD
        volumes:
            - /sessions
        networks:
            - backend
 
networks:
    front:
        external:
            name: front
    backend: